### ISSUE TITLE
Add Connection List View

### ISSUE THREAD

**Issue by karimStekelenburg** [animo/aries-mobile-agent-react-native#1]
Add a view that displays a list of connections.

### Todo
- [ ] Fetch agent connections from redux store
- [ ] Add list component
- [ ] Add `add connection` button that forwards to QR scan view

### Acceptation
- [ ]
