### ISSUE TITLE
Enable rn-indy-sdk support for iOS

### ISSUE THREAD

**Issue by karimStekelenburg** [animo/aries-mobile-agent-react-native#10]
### Feature description
Currently `rn-indy-sdk` only works on Android. We need to make sure it also runs in iOS.

### Todo
- [ ] Add Indy.Framework as stated in the [rn-indy-sdk docs](https://github.com/AbsaOSS/rn-indy-sdk/tree/docs/ios-install#ios)

### Review criteria
- [ ] App starts in iOS without problems
- [ ] Agent can be initialised
