### ISSUE TITLE
Create Connection Invitation Modal (ScannerView)

### ISSUE THREAD

**Issue by karimStekelenburg** [animo/aries-mobile-agent-react-native#6]
#### Todo
   - [ ] Show invitation details modal with `accept` and `decline` buttons
     - [ ] Implement `onDecline()`
       - [ ] Discard invitation
       - [ ] Redirect to 'home view' (not sure what that is yet)
     - [ ] Implement `onAccept()`
       - [ ] Import invitation into agent **with auto-accept enabled** (for now)
       - [ ] Redirect to `ConnectionsView`

#### Review criteria
- [ ] When user taps the `decline` button:
  - [ ] Connection not added to agent
- [ ] When user taps `accept` button:
  - [ ] Connection added to agent
