### ISSUE TITLE
Add accept/decline modal for connection invitation

### ISSUE THREAD

**Issue by karimStekelenburg** [animo/aries-mobile-agent-react-native#7]
### Feature description

Create a modal that shows the connection invitation after being scanned by the ScannerView (#2 )

### Todo
   - [ ] Show invitation details modal with `accept` and `decline` buttons
     - [ ] Implement `onDecline()`
       - [ ] Discard invitation
       - [ ] Redirect to 'home view' (not sure what that is yet)
     - [ ] Implement `onAccept()`
       - [ ] Import invitation into agent **with auto-accept enabled** (for now)
       - [ ] Redirect to `ConnectionsView`

### Review criteria
- [ ] When user taps the `decline` button:
  - [ ] Connection not in `ConnectionsView --> ConnectionsList`
- [ ] When user taps `accept` button:
  - [ ]  Connection added to `ConnectionsView --> ConnectionsList`
